version: '3'
services:
     
    pg: 
        image: postgres:latest
        container_name: xpaypgsql
    
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: test
            POSTGRES_PORT: 5432
            POSTGRES_HOST: localhost
            PGDATA: /var/lib/postgresql/data/pgdata 
           
        volumes:
            - ./db:/var/lib/postgresql/data            
        restart: always
    redis: 
        image: redis:latest
        container_name: xpayredis
        restart: always
        
  

    gotempl:  
        container_name: gotempl
        build: 
            context: ./
            dockerfile: ./udockerbot/Dockerfile  
            network: host 

        links:
            - pg
            - redis
        volumes: 
            - ./logs:/usr/src/app/logs #for logs             
        restart: always
   
        
    web:
        image : nginx:stable
        container_name: web
        ports:
        - "8080:8080"
        
        volumes: 
        - ./www:/var/www #for web
#        - ./nginx:/etc/nginx #for nginx conf
        restart: always    